name: Build Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install LLVM
        run: |
          mkdir deps && cd deps # https://github.com/MinaProtocol/mina/issues/8959#issuecomment-852183253
          sudo apt update
          wget http://de.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
          wget http://de.archive.ubuntu.com/ubuntu/pool/universe/j/jemalloc/libjemalloc1_3.6.0-11_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/main/p/procps/libprocps6_3.3.12-3ubuntu1_amd64.deb
          sudo dpkg -i *.deb
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main"
          cd ..
          rm -rf deps
          sudo apt-get update
          sudo apt-get install -y \
            llvm-13-dev libclang-13-dev clang-13 \
            liblld-13-dev liblld-13 lld-13 libllvm13 \
            llvm-13 llvm-13-tools libclang-cpp13 \
            libclang-common-13-dev libclang1-13
      - name: List Libs
        run: cd /usr/lib/cmake && ls
      - name: Create Build Directory
        run: mkdir build
      - name: Generate CMake Files
        run: cd build && cmake .. "-DCMAKE_PREFIX_PATH=/usr/lib/llvm-13/lib/cmake/llvm;/usr/lib/llvm-13/lib/cmake/clang;/usr/lib/llvm-13/lib/cmake/lld"
      - name: Build Project
        run: cd build && make
